### ISSUE TITLE
Getting VNDK errors while running the build

### ISSUE THREAD

**Issue by akash07k** [Wave-Project/device_xiaomi_surya#1]
@ghostrider-reborn Bro, I'm trying to run the build using your trees:
https://github.com/akash07k/device_xiaomi_surya
However, as soon as I run the build, I get these kind of errors instantly:
error: prebuilts/vndk/v28/arm/binder32/Android.bp:3306:1: module "libtinyxml2.vndk.28.arm.binder32" variant "android_vendor.28": field "arch.arm64.armv8_2a_dotprod" does not exist
error: prebuilts/vndk/v28/arm/binder32/Android.bp:3306:1: module "libtinyxml2.vndk.28.arm.binder32" variant "android_vendor.28": field "arch.arm64.armv8_2a_dotprod" does not exist.
error: prebuilts/vndk/v28/arm/binder32/Android.bp:3306:1: module "libtinyxml2.vndk.28.arm.binder32" variant "android_vendor.28": field "arch.arm64.armv8_2a_dotprod" does not exist.
error: prebuilts/vndk/v28/arm/binder32/Android.bp:3306:1: module "libtinyxml2.vndk.28.arm.binder32" variant "android_vendor.28": field "arch.arm64.armv8_2a_dotprod" does not exist

Can you please help me solving these errors? (These errors doesn't come when I use other trees, I'm getting these errors with your trees only, and your trees are the best, I want to use them).

**Comment by ghostrider-reborn** [comment]
You'll need to revert 0d304998152061e1a600a0e584e18eb0015e5da3.

**Comment by akash07k** [comment]
Thanks bro, I'll do that. and, is there any way if I want to use this
commit? I mean, this commit unlocks many other optimizations as per
your description, so, if I'll revert it, then I'll lose those
optimizations, hence, is there any way around to keep using this
commit and avoid the errors?

**Comment by ghostrider-reborn** [comment]
> Thanks bro, I'll do that. and, is there any way if I want to use this commit? I mean, this commit unlocks many other optimizations as per your description, so, if I'll revert it, then I'll lose those optimizations, hence, is there any way around to keep using this commit and avoid the errors?
> […](#)
> On 2/18/21, Ad!thya R ***@***.***> wrote: You'll need to revert [0d30499](https://github.com/Wave-Project/device_xiaomi_surya/commit/0d304998152061e1a600a0e584e18eb0015e5da3). -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#1 (comment)](https://github.com/Wave-Project/device_xiaomi_surya/issues/1#issuecomment-781300843)

You'll need few commits in build/make and build/soong and also newer clang 13 that requires commits in other repos as well.

**Comment by akash07k** [comment]
Oh, ok :(

**Comment by akash07k** [comment]
Do I have to revert any other commit bro? because now I'm getting
errors regarding Incorrect TARGET_SECOND_ARCH varient  and
target_arch_varient after reverting the commit which you told

**Comment by ghostrider-reborn** [comment]
> Do I have to revert any other commit bro? because now I'm getting errors regarding Incorrect TARGET_SECOND_ARCH varient and target_arch_varient after reverting the commit which you told
> […](#)
> On 2/18/21, Akash Kakkar ***@***.***> wrote: Oh, ok :( On 2/18/21, Ad!thya R ***@***.***> wrote: >> Thanks bro, I'll do that. and, is there any way if I want to use this >> commit? I mean, this commit unlocks many other optimizations as per your >> description, so, if I'll revert it, then I'll lose those optimizations, >> hence, is there any way around to keep using this commit and avoid the >> errors? >> […](#) >> On 2/18/21, Ad!thya R ***@***.***> wrote: You'll need to revert >> [[0d30499](https://github.com/Wave-Project/device_xiaomi_surya/commit/0d304998152061e1a600a0e584e18eb0015e5da3)]([0d30499](https://github.com/Wave-Project/device_xiaomi_surya/commit/0d304998152061e1a600a0e584e18eb0015e5da3)). >> -- You are receiving this because you authored the thread. Reply to this >> email directly or view it on GitHub: [#1 >> (comment)]([#1 (comment)](https://github.com/Wave-Project/device_xiaomi_surya/issues/1#issuecomment-781300843)) > > You'll need few commits in build/make and build/soong and also newer > clang > 13 that requires commits in other repos as well. > > -- > You are receiving this because you authored the thread. > Reply to this email directly or view it on GitHub: > [#1 (comment)](https://github.com/Wave-Project/device_xiaomi_surya/issues/1#issuecomment-781328584)

No.
